# Generated by Django 5.0.4 on 2024-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_businessdetails_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_names", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "Place List",
            },
        ),
    ]
