# Generated by Django 5.0.4 on 2024-04-27 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_placelist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlaceList",
        ),
    ]
