# Generated by Django 5.0.4 on 2024-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_placelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutocompleteSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_name", models.CharField(max_length=255)),
                ("search_image", models.URLField()),
                ("search_main", models.CharField(max_length=255)),
                ("business_id", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Autocomplete Search",
            },
        ),
    ]
