# Generated by Django 5.0.4 on 2024-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_autocompletesearch"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCarousel1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_image",
                    models.URLField(
                        default="https://t4.ftcdn.net/jpg/02/88/48/77/360_F_288487781_skjPODvR9bnuAGRVYP8AeRxT2AogzRHh.jpg"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Home Banner",
            },
        ),
    ]
