# Generated by Django 5.0.4 on 2024-05-09 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_homecarousel1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homecarousel1",
            old_name="banner_image",
            new_name="home_image",
        ),
    ]
