# Generated by Django 5.0.6 on 2024-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_banner_image_homecarousel1_home_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRModel",
            fields=[
                (
                    "chunk",
                    models.CharField(editable=False, primary_key=True, serialize=False),
                ),
                ("qr_image", models.URLField()),
                ("qr_link", models.URLField()),
                ("qr_redirect_link", models.URLField(default="https://digichola.in")),
                ("business_id", models.IntegerField(default=0)),
                ("business_phone_number", models.CharField(default="")),
                ("business_email", models.CharField(default="")),
                ("business_name", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name_plural": "QR Creator",
            },
        ),
        migrations.DeleteModel(
            name="AutocompleteSearch",
        ),
        migrations.DeleteModel(
            name="HomeCarousel1",
        ),
        migrations.RemoveField(
            model_name="onetimepassword",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlaceList",
        ),
        migrations.DeleteModel(
            name="OneTimePassword",
        ),
    ]
