# Generated by Django 5.0.6 on 2024-05-27 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_qrmodel_delete_autocompletesearch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutocompleteSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_name", models.CharField(max_length=255)),
                ("search_image", models.URLField()),
                ("search_main", models.CharField(max_length=255)),
                ("business_id", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Autocomplete Search",
            },
        ),
        migrations.CreateModel(
            name="HomeCarousel1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_image",
                    models.URLField(
                        default="https://t4.ftcdn.net/jpg/02/88/48/77/360_F_288487781_skjPODvR9bnuAGRVYP8AeRxT2AogzRHh.jpg"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Home Banner",
            },
        ),
        migrations.CreateModel(
            name="PlaceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_names", models.CharField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Place List",
            },
        ),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "OTP",
            },
        ),
    ]
