# Generated by Django 5.0.6 on 2024-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_autocompletesearch_homecarousel1_placelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrmodel",
            name="linked_status",
            field=models.BooleanField(default=False),
        ),
    ]
